=== Petross404/piklab/src/devices/pic/xml_data/pic.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- simple types definition -->
  <xs:simpleType name="hex">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9A-F]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hex4">
    <xs:restriction base="hex">
      <xs:length value="6"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="empty">
    <xs:restriction base="xs:string">
      <xs:length value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="word">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]+[A-Za-z0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EOL"/>
      <xs:enumeration value="NR"/>
      <xs:enumeration value="IP"/>
      <xs:enumeration value="Future"/>
      <xs:enumeration value="?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="memory_technology">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EE"/>
      <xs:enumeration value="EEE"/>
      <xs:enumeration value="EPROM"/>
      <xs:enumeration value="ROM"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="architecture">
    <xs:restriction base="xs:string">
      <xs:enumeration value="10X"/>
      <xs:enumeration value="16X"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="document_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
      <xs:pattern value="[?]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="errata_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+[a-z0-9]*"/>
      <xs:pattern value="er[a-z0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="erratas_type">
    <xs:list itemType="errata_type"/>
  </xs:simpleType>

  <xs:simpleType name="checksum_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="XOR4"/>
      <xs:enumeration value="XNOR7"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="frequency_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="commercial"/>
      <xs:enumeration value="industrial"/>
      <xs:enumeration value="extended"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frequency_special">
    <xs:restriction base="xs:string">
      <xs:enumeration value="low power"/>
      <xs:enumeration value="low voltage"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frequency_value">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="voltage_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vpp"/>
      <xs:enumeration value="vdd_prog"/>
      <xs:enumeration value="vdd_prog_write"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="voltage_value">
    <xs:restriction base="xs:float">
      <xs:minExclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="memory_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="program"/>
      <xs:enumeration value="eeprom"/>
      <xs:enumeration value="calibration"/>
      <xs:enumeration value="calibration_backup"/>
      <xs:enumeration value="user_ids"/>
      <xs:enumeration value="config"/>
      <xs:enumeration value="device_id"/>
      <xs:enumeration value="debug_vector"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hexfile_offset_unknown">
    <xs:restriction base="xs:string">
      <xs:enumeration value="?"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hexfile_offset">
    <xs:union memberTypes="hex hexfile_offset_unknown"/>
  </xs:simpleType>

  <xs:simpleType name="value_default_value">
    <xs:restriction base="xs:string">
      <xs:enumeration value="default"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="value_value">
    <xs:union memberTypes="hex value_default_value"/>
  </xs:simpleType>
  <xs:simpleType name="cname">
    <xs:restriction base="xs:string">
      <xs:pattern value="_[_0-9A-Za-z]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="cnames">
    <xs:list itemType="cname"/>
  </xs:simpleType>

  <xs:simpleType name="pin_name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z0-9-+]*(/[A-Z][A-Z0-9-+]*)*"/>
      <xs:pattern value="N/C"/>
      <xs:pattern value=""/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pin_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="dfns"/>
      <xs:enumeration value="mlf"/>
      <xs:enumeration value="mqfp"/>
      <xs:enumeration value="msop"/>
      <xs:enumeration value="pdip"/>
      <xs:enumeration value="plcc"/>
      <xs:enumeration value="qfn"/>
      <xs:enumeration value="sdip"/>
      <xs:enumeration value="soic"/>
      <xs:enumeration value="sot23"/>
      <xs:enumeration value="spdip"/>
      <xs:enumeration value="ssop"/>
      <xs:enumeration value="tqfp"/>
      <xs:enumeration value="tssop"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pin_types">
    <xs:list itemType="pin_type"/>
  </xs:simpleType>

<!-- complex types definition -->
  <xs:complexType name="DocumentsType">
    <xs:attribute name="webpage"       type="document_type" use="required"/>
    <xs:attribute name="datasheet"     type="document_type" use="required"/>
    <xs:attribute name="progsheet"     type="document_type" use="required"/>
    <xs:attribute name="erratas"       type="erratas_type"  use="required"/>
  </xs:complexType>

  <xs:complexType name="ChecksumType">
    <xs:attribute name="protected"       type="xs:string" />
    <xs:attribute name="type"            type="checksum_type" />
    <xs:attribute name="constant"        type="hex4" />
    <xs:attribute name="block_protected" type="xs:nonNegativeInteger"/>
    <xs:attribute name="bbsize"          type="xs:positiveInteger"/>
    <xs:attribute name="mprotected"      type="word"/>
    <xs:attribute name="bchecksum"       type="hex4" use="required"/>
    <xs:attribute name="cchecksum"       type="hex4" use="required"/>
  </xs:complexType>
  <xs:complexType name="ChecksumsType">
    <xs:sequence>
      <xs:element name="checksum" type="ChecksumType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="FrequencyType">
    <xs:attribute name="start"       type="frequency_value" use="required"/>
    <xs:attribute name="end"         type="frequency_value" use="required"/>
    <xs:attribute name="vdd_min"     type="voltage_value"   use="required"/>
    <xs:attribute name="vdd_min_end" type="voltage_value"                 />
    <xs:attribute name="vdd_max"     type="voltage_value"   use="required"/>
    <xs:attribute name="special"     type="xs:string"                     />
    <xs:attribute name="osc"         type="xs:string"                     />
  </xs:complexType>
  <xs:complexType name="FrequencyRangeType">
    <xs:sequence>
      <xs:element name="frequency" type="FrequencyType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="frequency_type"    use="required"/>
    <xs:attribute name="special" type="frequency_special"               />
  </xs:complexType>

  <xs:complexType name="VoltagesType">
    <xs:attribute name="name"    type="voltage_type"  use="required"/>
    <xs:attribute name="min"     type="voltage_value" use="required"/>
    <xs:attribute name="max"     type="voltage_value" use="required"/>
    <xs:attribute name="nominal" type="voltage_value" use="required"/>
  </xs:complexType>

  <xs:complexType name="MemoryType">
    <xs:attribute name="name"           type="memory_type"   use="required"/>
    <xs:attribute name="start"          type="hex"           use="required"/>
    <xs:attribute name="end"            type="hex"           use="required"/>
    <xs:attribute name="cal_opmask"     type="hex"                         />
    <xs:attribute name="cal_opcode"     type="hex"                         />
    <xs:attribute name="rmask"          type="hex"                         />
    <xs:attribute name="hexfile_offset" type="hexfile_offset"              />
  </xs:complexType>

  <xs:complexType name="ValueType">
    <xs:attribute name="name"    type="xs:string"   use="required"/>
    <xs:attribute name="value"   type="value_value" use="required"/>
    <xs:attribute name="cname"   type="cnames"                    />
    <xs:attribute name="ecnames" type="cnames"                    />
  </xs:complexType>
  <xs:complexType name="MaskType">
    <xs:sequence>
      <xs:element name="value" type="ValueType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"   type="word" use="required"/>
    <xs:attribute name="value"  type="hex"  use="required"/>
  </xs:complexType>
  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="mask" type="MaskType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="xs:string" use="required"/>
    <xs:attribute name="offset"  type="hex"       use="required"/>
    <xs:attribute name="wmask"   type="hex"       use="required"/>
    <xs:attribute name="bvalue"  type="hex"       use="required"/>
    <xs:attribute name="cmask"   type="hex"                     />
    <xs:attribute name="pmask"   type="hex"                     />
    <xs:attribute name="icnames" type="cnames"                  />
  </xs:complexType>

  <xs:complexType name="PinType">
    <xs:attribute name="index" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="name"  type="pin_name"                         />
  </xs:complexType>
  <xs:complexType name="PackageType">
    <xs:sequence>
      <xs:element name="pin" type="PinType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="types"    type="pin_types"          use="required"/>
    <xs:attribute name="nb_pins"  type="xs:positiveInteger" use="required"/>
  </xs:complexType>

<!-- document -->
  <xs:complexType name="deviceType">
    <xs:sequence>
      <xs:element name="documents"       type="DocumentsType"      minOccurs="0"        />
      <xs:element name="checksums"       type="ChecksumsType"      minOccurs="0"        />
      <xs:element name="frequency_range" type="FrequencyRangeType" maxOccurs="unbounded"/>
      <xs:element name="voltages"        type="VoltagesType"       maxOccurs="unbounded"/>
      <xs:element name="memory"          type="MemoryType"         maxOccurs="unbounded"/>
      <xs:element name="config"          type="ConfigType"         maxOccurs="unbounded"/>
      <xs:element name="package"         type="PackageType"        maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"              type="xs:string"         use="required"/>
    <xs:attribute name="alternative"       type="xs:string"                       />
    <xs:attribute name="document"          type="document_type"                   />
    <xs:attribute name="status"            type="status"            use="required"/>
    <xs:attribute name="memory_technology" type="memory_technology" use="required"/>
    <xs:attribute name="architecture"      type="architecture"      use="required"/>
    <xs:attribute name="pc"                type="xs:positiveInteger"              />
    <xs:attribute name="id"                type="hex4"                            />
  </xs:complexType>

  <xs:element name="device" type="deviceType"/>

</xs:schema>

=== Petross404/piklab/src/devices/pic/xml_data/10F320.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2012 Nicolas Hadacek <hadacek@kde.org>                 *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="10F320" status="IP" memory_technology="FLASH" self_write="yes" architecture="midrange" id="0x29A0"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Documents ************************************************************-->
  <documents webpage="552961" datasheet="41585" progsheet="41572" erratas="80529" />

<!--* Checksums ************************************************************-->
  <checksums>
    <checksum protected="Off" bchecksum="0x1EFF" cchecksum="0xA055" />
    <checksum protected="All" bchecksum="0x372E" cchecksum="0xB854" />
  </checksums>

<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" >
    <frequency start="0"  end="16" vdd_min="2.3" vdd_max="5.5" />
    <frequency start="16" end="20" vdd_min="2.5" vdd_max="5.5" />
  </frequency_range>

  <voltages name="vpp"      min="8"   max="9"   nominal="8.5" />
  <voltages name="vdd_prog" min="2.7" max="5.5" nominal="5"  />

<!--* Memory ***************************************************************-->
  <memory name="code"               start="0x0000" end="0x00FF" />
  <memory name="calibration"        start="0x2008" end="0x2009" cal_opmask="0x0000" cal_opcode="0x0000"/>
  <memory name="user_ids"           start="0x2000" end="0x2003" rmask="0x000F" />
  <memory name="config"             start="0x2007" end="0x2007" />
  <memory name="device_id"          start="0x2006" end="0x2006" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="" wmask="0x3FFF" bvalue="0x3FFF" >
    <mask name="FOSC"   value="0x0001" >
      <value value="0x0000" name="INTRC" def="_FOSC_INTOSC" />
      <value value="0x0001" name="EC"     def="_FOSC_EC"     />
    </mask>
    <mask name="BODEN"  value="0x0006" >
      <value value="0x0000" name="Off"      def="_BOREN_OFF"    />
      <value value="0x0002" name="Software" def="_BOREN_SBODEN" />
      <value value="0x0004" name="On_run"   def="_BOREN_NSLEEP" />
      <value value="0x0006" name="On"       def="_BOREN_ON"     />
    </mask>
    <mask name="WDT"    value="0x0018" >
      <value value="0x0000" name="Off"      def="_WDT_OFF"    />
      <value value="0x0008" name="Software" def="_WDT_SWDTEN" />
      <value value="0x0010" name="On_run"   def="_WDT_NSLEEP" />
      <value value="0x0018" name="On"       def="_WDT_ON"     />
    </mask>
    <mask name="PWRTE"  value="0x0020" >
      <value value="0x0000" name="On"  def="_PWRTE_ON"  />
      <value value="0x0020" name="Off" def="_PWRTE_OFF" />
    </mask>
    <mask name="MCLRE"  value="0x0040" >
      <value value="0x0000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x0040" name="External" def="_MCLRE_ON"  />
    </mask>
    <mask name="CP"  value="0x0080" >
      <value value="0x0000" name="All" def="_CP_ON"  />
      <value value="0x0080" name="Off" def="_CP_OFF" />
    </mask>
    <mask name="LVP"  value="0x0100" >
      <value value="0x0000" name="Off" def="_LVP_OFF" />
      <value value="0x0100" name="On"  def="_LVP_ON"  />
    </mask>
    <mask name="LPBOR"  value="0x0200" >
      <value value="0x0000" name="Off" def="_LPBOR_OFF" />
      <value value="0x0200" name="On"  def="_LPBOR_ON"  />
    </mask>
    <mask name="BORV"  value="0x0400" >
      <value value="0x0000" name="2.7" def="_BORV_27" />
      <value value="0x0400" name="2.4" def="_BORV_24"  />
    </mask>
    <mask name="WRT"  value="0x1800" >
      <value value="0x0000" name="000:0FF" def="_WRT_ALL" />
      <value value="0x0800" name="000:07F" def="_WRT_HALF"  />
      <value value="0x1000" name="000:03F" def="_WRT_BOOT"  />
      <value value="0x1800" name="Off"     def="_WRT_OFF"  />
    </mask>
    <mask name="DEBUG"  value="0x2000" >
      <value value="0x0000" name="On"   def="_DEBUG_OFF" />
      <value value="0x2000" name="Off"  def="_DEBUG_ON"  />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip"  nb_pins="8" >
    <pin index="1" name="N/C"          />
    <pin index="2" name="VDD"          />
    <pin index="3" name="RA2"          />
    <pin index="4" name="RA1/ISCPCLK"  />
    <pin index="5" name="RA3/MCLR/VPP" />
    <pin index="6" name="VSS"          />
    <pin index="7" name="N/C"          />
    <pin index="8" name="RA0/ISCPDAT"  />
  </package>

  <package types="sot23" nb_pins="6" >
    <pin index="1" name="RA0/ISCPDAT"  />
    <pin index="2" name="VSS"          />
    <pin index="3" name="RA2"          />
    <pin index="4" name="RA1/ISCPCLK"  />
    <pin index="5" name="VDD"          />
    <pin index="6" name="RA3/MCLR/VPP" />
  </package>

</device>

=== Petross404/piklab/src/devices/pic/xml_data/16F724.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2010 Nicolas Hadacek <hadacek@kde.org>                 *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="16F724" status="IP" memory_technology="FLASH" self_write="no" architecture="midrange" id="0x1840"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Documents ************************************************************-->
  <documents webpage="533509" datasheet="41341" progsheet="41332" erratas="80382" />

<!--* Checksums ************************************************************-->
<!--  <checksums>
    <checksum protected="Off" bchecksum="0xF85F" cchecksum="0x842D" />
    <checksum protected="All" bchecksum="0x005E" cchecksum="0x005E" />
  </checksums>
-->
<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" special="low_power" >
    <frequency start="0"  end="16" vdd_min="1.8" vdd_max="3.6" />
    <frequency start="16" end="20" vdd_min="2.3" vdd_max="3.6" />
  </frequency_range>
  <frequency_range name="extended"   >
    <frequency start="0"  end="16" vdd_min="1.8" vdd_max="5.5" />
    <frequency start="16" end="20" vdd_min="2.3" vdd_max="5.5" />
  </frequency_range>

  <voltages name="vpp"           min="8.0" max="9.0" nominal="8.5" />
  <voltages name="vdd_prog"      min="2.7" max="5.5" nominal="5.0"  />

<!--* Memory ***************************************************************-->
  <memory name="code"         start="0x0000" end="0x0FFF" />
  <memory name="user_ids"     start="0x2000" end="0x2003" rmask="0x000F" />
  <memory name="debug_vector" start="0x2004" end="0x2004" />
  <memory name="device_id"    start="0x2006" end="0x2006" />
  <memory name="config"       start="0x2007" end="0x2008" />
  <memory name="calibration"  start="0x2009" end="0x200A" cal_opcode="0x0000" cal_opmask="0x0000" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="CONFIG1" wmask="0x3FFF" bvalue="0x3740" >
    <mask name="FOSC"  value="0x0007" >
      <value value="0x0000" name="LP"           def="_LP_OSC" />
      <value value="0x0001" name="XT"           def="_XT_OSC" />
      <value value="0x0002" name="HS"           def="_HS_OSC" />
      <value value="0x0003" name="EC_IO"        def="_EC_OSC" />
      <value value="0x0004" name="INTRC_IO"     def="_INTRC_OSC_NOCLKOUT _INTOSCIO" />
      <value value="0x0005" name="INTRC_CLKOUT" def="_INTRC_OSC_CLKOUT _INTOSC" />
      <value value="0x0006" name="EXTRC_IO"     def="_EXTRC_OSC_NOCLKOUT _EXTRCIO" />
      <value value="0x0007" name="EXTRC_CLKOUT" def="_EXTRC_OSC_CLKOUT _EXTRC" />
    </mask>
    <mask name="WDT"   value="0x0008" >
      <value value="0x0000" name="Off" def="_WDT_OFF" />
      <value value="0x0008" name="On"  def="_WDT_ON"  />
    </mask>
    <mask name="PWRTE" value="0x0010" >
      <value value="0x0000" name="On"  def="_PWRT_EN"  />
      <value value="0x0010" name="Off" def="_PWRT_DIS" />
    </mask>
    <mask name="MCLRE" value="0x0020" >
      <value value="0x0000" name="Internal" def="_MCLR_DIS" />
      <value value="0x0020" name="External" def="_MCLR_EN"  />
    </mask>
    <mask name="CP"    value="0x0040" >
      <value value="0x0000" name="All" def="_CP_ON" />
      <value value="0x0040" name="Off" def="_CP_OFF" />
    </mask>
    <mask name="BODEN" value="0x0300" >
      <value value="default" name="Off"    def="_BOR_OFF"    />
      <value value="0x0200"  name="On_run" def="_BOR_NSLEEP" />
      <value value="0x0300"  name="On"     def="_BOR_ON"     />
    </mask>
    <mask name="BORV"  value="0x0400" >
      <value value="0x0000" name="2.5" def="_BORV_2_5" />
      <value value="0x0400" name="1.9" def="_BORV_1_9" />
    </mask>
    <mask name="PLLEN" value="0x1000" >
      <value value="0x0000" name="Off" def="_PLL_DIS" />
      <value value="0x1000" name="On"  def="_PLL_EN" />
    </mask>
    <mask name="DEBUG" value="0x2000" >
      <value value="0x0000" name="On"  def="_DEBUG_ON"  />
      <value value="0x2000" name="Off" def="_DEBUG_OFF" />
    </mask>
  </config>

  <config offset="0x1" name="CONFIG2" wmask="0x3FFF" bvalue="0x0030" >
    <mask name="VCAP" value="0x0030" >
      <value value="0x0000" name="RA0"  def="_VCAP_RA0" />
      <value value="0x0010" name="RA5"  def="_VCAP_RA5" />
      <value value="0x0020" name="RA6"  def="_VCAP_RA6" />
      <value value="0x0030" name="Off"  def="_VCAP_DIS" />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip" nb_pins="40" >
    <pin index="1"  name="" />
    <pin index="2"  name="" />
    <pin index="3"  name="" />
    <pin index="4"  name="" />
    <pin index="5"  name="" />
    <pin index="6"  name="" />
    <pin index="7"  name="" />
    <pin index="8"  name="" />
    <pin index="9"  name="" />
    <pin index="10" name="" />
    <pin index="11" name="" />
    <pin index="12" name="" />
    <pin index="13" name="" />
    <pin index="14" name="" />
    <pin index="15" name="" />
    <pin index="16" name="" />
    <pin index="17" name="" />
    <pin index="18" name="" />
    <pin index="19" name="" />
    <pin index="20" name="" />
    <pin index="21" name="" />
    <pin index="22" name="" />
    <pin index="23" name="" />
    <pin index="24" name="" />
    <pin index="25" name="" />
    <pin index="26" name="" />
    <pin index="27" name="" />
    <pin index="28" name="" />
    <pin index="29" name="" />
    <pin index="30" name="" />
    <pin index="31" name="" />
    <pin index="32" name="" />
    <pin index="33" name="" />
    <pin index="34" name="" />
    <pin index="35" name="" />
    <pin index="36" name="" />
    <pin index="37" name="" />
    <pin index="38" name="" />
    <pin index="39" name="" />
    <pin index="40" name="" />
  </package>

  <package types="tqfp" nb_pins="44" >
    <pin index="1"  name="" />
    <pin index="2"  name="" />
    <pin index="3"  name="" />
    <pin index="4"  name="" />
    <pin index="5"  name="" />
    <pin index="6"  name="" />
    <pin index="7"  name="" />
    <pin index="8"  name="" />
    <pin index="9"  name="" />
    <pin index="10" name="" />
    <pin index="11" name="" />
    <pin index="12" name="" />
    <pin index="13" name="" />
    <pin index="14" name="" />
    <pin index="15" name="" />
    <pin index="16" name="" />
    <pin index="17" name="" />
    <pin index="18" name="" />
    <pin index="19" name="" />
    <pin index="20" name="" />
    <pin index="21" name="" />
    <pin index="22" name="" />
    <pin index="23" name="" />
    <pin index="24" name="" />
    <pin index="25" name="" />
    <pin index="26" name="" />
    <pin index="27" name="" />
    <pin index="28" name="" />
    <pin index="29" name="" />
    <pin index="30" name="" />
    <pin index="31" name="" />
    <pin index="32" name="" />
    <pin index="33" name="" />
    <pin index="34" name="" />
    <pin index="35" name="" />
    <pin index="36" name="" />
    <pin index="37" name="" />
    <pin index="38" name="" />
    <pin index="39" name="" />
    <pin index="40" name="" />
    <pin index="41" name="" />
    <pin index="42" name="" />
    <pin index="43" name="" />
    <pin index="44" name="" />
  </package>

</device>

=== Petross404/piklab/src/devices/pic/xml_data/14000.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2005-2007 Nicolas Hadacek <hadacek@kde.org>            *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="14000" document="010116" status="NR" alternative="16F883" memory_technology="EPROM" architecture="midrange"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Checksums ************************************************************-->
  <checksums>
    <checksum protected="Off"                  bchecksum="0x2FFD" cchecksum="0xFBCB" />
    <checksum protected="All" mprotected="CPC" bchecksum="0x300A" cchecksum="0xFBD8" />
  </checksums>

<!--* Operating characteristics ********************************************-->
  <frequency_range name="industrial" >
    <frequency start="0" end="4"  vdd_min="2.7" vdd_max="6"   />
    <frequency start="4" end="20" vdd_min="4.5" vdd_max="5.5" />
  </frequency_range>

  <voltages name="vpp"      min="12.75" max="13.25" nominal="13" />
  <voltages name="vdd_prog" min="4.75"  max="5.25"  nominal="5"  />

<!--* Memory ***************************************************************-->
  <memory name="code"     start="0x0000" end="0x0FBF" />
  <memory name="calibration" start="0x0FC0" end="0x0FFF" cal_opmask="0x0000" cal_opcode="0x0000" />
  <memory name="user_ids"    start="0x2000" end="0x2003" rmask="0x007F"      />
  <memory name="config"      start="0x2007" end="0x2007" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="" wmask="0x3FFF" bvalue="0x3FBD" pmask="0x0042" >
    <mask name="FOSC"  value="0x0001" >
      <value value="0x0000" name="HS"    def="_FOSC_HS" />
      <value value="0x0001" name="INTRC" def="_FOSC_RC" />
    </mask>
    <mask name="WDT"   value="0x0004" >
      <value value="0x0000" name="Off" def="_WDT_OFF" />
      <value value="0x0004" name="On"  def="_WDT_ON"  />
    </mask>
    <mask name="PWRTE" value="0x0008" >
      <value value="0x0000" name="On"  def="_PWRTE_ON"  />
      <value value="0x0008" name="Off" def="_PWRTE_OFF" />
    </mask>
    <mask name="TRIM" value="0x0042" >
      <value value="0x0000" name="00" />
      <value value="0x0002" name="01" />
      <value value="0x0040" name="10" />
      <value value="0x0042" name="11" />
    </mask>
    <mask name="CP"    value="0x1E30" >
      <value value="0x0000"  name="All" def="_CPP_ON _CPU_ON"   />
      <value value="0x1E30"  name="Off" def="_CPP_OFF _CPU_OFF" />
      <value value="default" name="invalid" />
    </mask>
    <mask name="CPC"   value="0x2180" >
      <value value="0x0000"  name="All" def="_CPC_ON"  />
      <value value="0x2180"  name="Off" def="_CPC_OFF" />
      <value value="default" name="invalid" />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip soic" nb_pins="28" >
    <pin index="1"  name="" />
    <pin index="2"  name="" />
    <pin index="3"  name="" />
    <pin index="4"  name="" />
    <pin index="5"  name="" />
    <pin index="6"  name="" />
    <pin index="7"  name="" />
    <pin index="8"  name="" />
    <pin index="9"  name="" />
    <pin index="10" name="" />
    <pin index="11" name="" />
    <pin index="12" name="" />
    <pin index="13" name="" />
    <pin index="14" name="" />
    <pin index="15" name="" />
    <pin index="16" name="" />
    <pin index="17" name="" />
    <pin index="18" name="" />
    <pin index="19" name="" />
    <pin index="20" name="" />
    <pin index="21" name="" />
    <pin index="22" name="" />
    <pin index="23" name="" />
    <pin index="24" name="" />
    <pin index="25" name="" />
    <pin index="26" name="" />
    <pin index="27" name="" />
    <pin index="28" name="" />
  </package>

</device>
