=== Petross404/piklab/src/devices/pic/xml_data/pic.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- simple types definition -->
  <xs:simpleType name="hex">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9A-F]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hex4">
    <xs:restriction base="hex">
      <xs:length value="6"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="empty">
    <xs:restriction base="xs:string">
      <xs:length value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="word">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]+[A-Za-z0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EOL"/>
      <xs:enumeration value="NR"/>
      <xs:enumeration value="IP"/>
      <xs:enumeration value="Future"/>
      <xs:enumeration value="?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="memory_technology">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EE"/>
      <xs:enumeration value="EEE"/>
      <xs:enumeration value="EPROM"/>
      <xs:enumeration value="ROM"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="architecture">
    <xs:restriction base="xs:string">
      <xs:enumeration value="10X"/>
      <xs:enumeration value="16X"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="document_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
      <xs:pattern value="[?]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="errata_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+[a-z0-9]*"/>
      <xs:pattern value="er[a-z0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="erratas_type">
    <xs:list itemType="errata_type"/>
  </xs:simpleType>

  <xs:simpleType name="checksum_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="XOR4"/>
      <xs:enumeration value="XNOR7"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="frequency_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="commercial"/>
      <xs:enumeration value="industrial"/>
      <xs:enumeration value="extended"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frequency_special">
    <xs:restriction base="xs:string">
      <xs:enumeration value="low power"/>
      <xs:enumeration value="low voltage"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frequency_value">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="voltage_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vpp"/>
      <xs:enumeration value="vdd_prog"/>
      <xs:enumeration value="vdd_prog_write"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="voltage_value">
    <xs:restriction base="xs:float">
      <xs:minExclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="memory_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="program"/>
      <xs:enumeration value="eeprom"/>
      <xs:enumeration value="calibration"/>
      <xs:enumeration value="calibration_backup"/>
      <xs:enumeration value="user_ids"/>
      <xs:enumeration value="config"/>
      <xs:enumeration value="device_id"/>
      <xs:enumeration value="debug_vector"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hexfile_offset_unknown">
    <xs:restriction base="xs:string">
      <xs:enumeration value="?"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hexfile_offset">
    <xs:union memberTypes="hex hexfile_offset_unknown"/>
  </xs:simpleType>

  <xs:simpleType name="value_default_value">
    <xs:restriction base="xs:string">
      <xs:enumeration value="default"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="value_value">
    <xs:union memberTypes="hex value_default_value"/>
  </xs:simpleType>
  <xs:simpleType name="cname">
    <xs:restriction base="xs:string">
      <xs:pattern value="_[_0-9A-Za-z]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="cnames">
    <xs:list itemType="cname"/>
  </xs:simpleType>

  <xs:simpleType name="pin_name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z0-9-+]*(/[A-Z][A-Z0-9-+]*)*"/>
      <xs:pattern value="N/C"/>
      <xs:pattern value=""/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pin_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="dfns"/>
      <xs:enumeration value="mlf"/>
      <xs:enumeration value="mqfp"/>
      <xs:enumeration value="msop"/>
      <xs:enumeration value="pdip"/>
      <xs:enumeration value="plcc"/>
      <xs:enumeration value="qfn"/>
      <xs:enumeration value="sdip"/>
      <xs:enumeration value="soic"/>
      <xs:enumeration value="sot23"/>
      <xs:enumeration value="spdip"/>
      <xs:enumeration value="ssop"/>
      <xs:enumeration value="tqfp"/>
      <xs:enumeration value="tssop"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pin_types">
    <xs:list itemType="pin_type"/>
  </xs:simpleType>

<!-- complex types definition -->
  <xs:complexType name="DocumentsType">
    <xs:attribute name="webpage"       type="document_type" use="required"/>
    <xs:attribute name="datasheet"     type="document_type" use="required"/>
    <xs:attribute name="progsheet"     type="document_type" use="required"/>
    <xs:attribute name="erratas"       type="erratas_type"  use="required"/>
  </xs:complexType>

  <xs:complexType name="ChecksumType">
    <xs:attribute name="protected"       type="xs:string" />
    <xs:attribute name="type"            type="checksum_type" />
    <xs:attribute name="constant"        type="hex4" />
    <xs:attribute name="block_protected" type="xs:nonNegativeInteger"/>
    <xs:attribute name="bbsize"          type="xs:positiveInteger"/>
    <xs:attribute name="mprotected"      type="word"/>
    <xs:attribute name="bchecksum"       type="hex4" use="required"/>
    <xs:attribute name="cchecksum"       type="hex4" use="required"/>
  </xs:complexType>
  <xs:complexType name="ChecksumsType">
    <xs:sequence>
      <xs:element name="checksum" type="ChecksumType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="FrequencyType">
    <xs:attribute name="start"       type="frequency_value" use="required"/>
    <xs:attribute name="end"         type="frequency_value" use="required"/>
    <xs:attribute name="vdd_min"     type="voltage_value"   use="required"/>
    <xs:attribute name="vdd_min_end" type="voltage_value"                 />
    <xs:attribute name="vdd_max"     type="voltage_value"   use="required"/>
    <xs:attribute name="special"     type="xs:string"                     />
    <xs:attribute name="osc"         type="xs:string"                     />
  </xs:complexType>
  <xs:complexType name="FrequencyRangeType">
    <xs:sequence>
      <xs:element name="frequency" type="FrequencyType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="frequency_type"    use="required"/>
    <xs:attribute name="special" type="frequency_special"               />
  </xs:complexType>

  <xs:complexType name="VoltagesType">
    <xs:attribute name="name"    type="voltage_type"  use="required"/>
    <xs:attribute name="min"     type="voltage_value" use="required"/>
    <xs:attribute name="max"     type="voltage_value" use="required"/>
    <xs:attribute name="nominal" type="voltage_value" use="required"/>
  </xs:complexType>

  <xs:complexType name="MemoryType">
    <xs:attribute name="name"           type="memory_type"   use="required"/>
    <xs:attribute name="start"          type="hex"           use="required"/>
    <xs:attribute name="end"            type="hex"           use="required"/>
    <xs:attribute name="cal_opmask"     type="hex"                         />
    <xs:attribute name="cal_opcode"     type="hex"                         />
    <xs:attribute name="rmask"          type="hex"                         />
    <xs:attribute name="hexfile_offset" type="hexfile_offset"              />
  </xs:complexType>

  <xs:complexType name="ValueType">
    <xs:attribute name="name"    type="xs:string"   use="required"/>
    <xs:attribute name="value"   type="value_value" use="required"/>
    <xs:attribute name="cname"   type="cnames"                    />
    <xs:attribute name="ecnames" type="cnames"                    />
  </xs:complexType>
  <xs:complexType name="MaskType">
    <xs:sequence>
      <xs:element name="value" type="ValueType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"   type="word" use="required"/>
    <xs:attribute name="value"  type="hex"  use="required"/>
  </xs:complexType>
  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="mask" type="MaskType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="xs:string" use="required"/>
    <xs:attribute name="offset"  type="hex"       use="required"/>
    <xs:attribute name="wmask"   type="hex"       use="required"/>
    <xs:attribute name="bvalue"  type="hex"       use="required"/>
    <xs:attribute name="cmask"   type="hex"                     />
    <xs:attribute name="pmask"   type="hex"                     />
    <xs:attribute name="icnames" type="cnames"                  />
  </xs:complexType>

  <xs:complexType name="PinType">
    <xs:attribute name="index" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="name"  type="pin_name"                         />
  </xs:complexType>
  <xs:complexType name="PackageType">
    <xs:sequence>
      <xs:element name="pin" type="PinType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="types"    type="pin_types"          use="required"/>
    <xs:attribute name="nb_pins"  type="xs:positiveInteger" use="required"/>
  </xs:complexType>

<!-- document -->
  <xs:complexType name="deviceType">
    <xs:sequence>
      <xs:element name="documents"       type="DocumentsType"      minOccurs="0"        />
      <xs:element name="checksums"       type="ChecksumsType"      minOccurs="0"        />
      <xs:element name="frequency_range" type="FrequencyRangeType" maxOccurs="unbounded"/>
      <xs:element name="voltages"        type="VoltagesType"       maxOccurs="unbounded"/>
      <xs:element name="memory"          type="MemoryType"         maxOccurs="unbounded"/>
      <xs:element name="config"          type="ConfigType"         maxOccurs="unbounded"/>
      <xs:element name="package"         type="PackageType"        maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"              type="xs:string"         use="required"/>
    <xs:attribute name="alternative"       type="xs:string"                       />
    <xs:attribute name="document"          type="document_type"                   />
    <xs:attribute name="status"            type="status"            use="required"/>
    <xs:attribute name="memory_technology" type="memory_technology" use="required"/>
    <xs:attribute name="architecture"      type="architecture"      use="required"/>
    <xs:attribute name="pc"                type="xs:positiveInteger"              />
    <xs:attribute name="id"                type="hex4"                            />
  </xs:complexType>

  <xs:element name="device" type="deviceType"/>

</xs:schema>

=== Petross404/piklab/src/devices/pic/xml_data/16C781.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2005-2007 Nicolas Hadacek <hadacek@kde.org>            *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="16C781" document="010178" status="NR"
        memory_technology="EPROM" architecture="midrange" id="0x0D40"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Checksums ************************************************************-->
  <checksums>
    <checksum protected="Off"     bchecksum="0x3B7F" cchecksum="0x074D" />
    <checksum protected="All"     bchecksum="0x47FE" cchecksum="0x13CC" />
  </checksums>

<!--* Operating characteristics ********************************************-->
  <frequency_range name="industrial" >
    <frequency start="0" end="4"  vdd_min="4"   vdd_max="5.5" />
    <frequency start="4" end="20" vdd_min="4.5" vdd_max="5.5" />
  </frequency_range>
  <frequency_range name="industrial" special="low_power" >
    <frequency start="0" end="4"  vdd_min="2.7" vdd_max="5.5" />
    <frequency start="4" end="20" vdd_min="4.5" vdd_max="5.5" />
  </frequency_range>

  <voltages name="vpp"      min="12.75" max="13.25" nominal="13" />
  <voltages name="vdd_prog" min="4.75"  max="5.25"  nominal="5"  />

<!--* Memory ***************************************************************-->
  <memory name="code"   start="0x0000" end="0x03FF" />
  <memory name="user_ids"  start="0x2000" end="0x2003" rmask="0x007F" />
  <memory name="device_id" start="0x2006" end="0x2006" />
  <memory name="config"    start="0x2007" end="0x2007" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="" wmask="0x3FFF" bvalue="0x3F7F" >
    <mask name="FOSC"  value="0x0007" >
      <value value="0x0000" name="LP"           def="_LP_OSC"             />
      <value value="0x0001" name="XT"           def="_XT_OSC"             />
      <value value="0x0002" name="HS"           def="_HS_OSC"             />
      <value value="0x0003" name="EC_IO"        def="_EXTCLK_OSC"         />
      <value value="0x0004" name="INTRC_IO"     def="_INTRC_OSC_NOCLKOUT" />
      <value value="0x0005" name="INTRC_CLKOUT" def="_INTRC_OSC_CLKOUT"   />
      <value value="0x0006" name="ER_IO"        def="_ER_OSC_NOCLKOUT"    />
      <value value="0x0007" name="ER_CLKOUT"    def="_ER_OSC_CLKOUT"      />
    </mask>
    <mask name="WDT"   value="0x0008" >
      <value value="0x0000" name="Off" def="_WDT_OFF" />
      <value value="0x0008" name="On"  def="_WDT_ON"  />
    </mask>
    <mask name="PWRTE" value="0x0010" >
      <value value="0x0000" name="On"  def="_PWRTE_ON"  />
      <value value="0x0010" name="Off" def="_PWRTE_OFF" />
    </mask>
    <mask name="MCLRE" value="0x0020" >
      <value value="0x0000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x0020" name="External" def="_MCLRE_ON"  />
    </mask>
    <mask name="BODEN" value="0x0040" >
      <value value="0x0000" name="Off" def="_BODEN_OFF" />
      <value value="0x0040" name="On"  def="_BODEN_ON"  />
    </mask>
    <mask name="BORV"  value="0x0C00" >
      <value value="0x0000" name="4.5" def="_VBOR_45" />
      <value value="0x0400" name="4.2" def="_VBOR_42" />
      <value value="0x0800" name="2.7" def="_VBOR_27" />
      <value value="0x0C00" name="2.5" def="_VBOR_25" />
    </mask>
    <mask name="CP"    value="0x3300" >
      <value value="0x0000" name="All" def="_CP_ALL" />
      <value value="0x3300" name="Off" def="_CP_OFF" />
      <value value="default" name="invalid" />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip soic ssop" nb_pins="20" >
    <pin index="1"  name="" />
    <pin index="2"  name="" />
    <pin index="3"  name="" />
    <pin index="4"  name="" />
    <pin index="5"  name="" />
    <pin index="6"  name="" />
    <pin index="7"  name="" />
    <pin index="8"  name="" />
    <pin index="9"  name="" />
    <pin index="10" name="" />
    <pin index="11" name="" />
    <pin index="12" name="" />
    <pin index="13" name="" />
    <pin index="14" name="" />
    <pin index="15" name="" />
    <pin index="16" name="" />
    <pin index="17" name="" />
    <pin index="18" name="" />
    <pin index="19" name="" />
    <pin index="20" name="" />
  </package>

</device>

=== Petross404/piklab/src/devices/pic/xml_data/16F1507.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2011 Gal Zsolt                                         *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="16F1507" status="IP" memory_technology="FLASH" self_write="yes"
        architecture="emidrange" id="0x2D00" id_low_power="0x2DC0"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Documents ************************************************************-->
  <documents webpage="553468" datasheet="41586" progsheet="41573" erratas="" />

<!--* Checksums ************************************************************-->

<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" >
    <frequency start="0"  end="16" vdd_min="2.3" vdd_max="5.5" />
    <frequency start="16" end="32" vdd_min="2.5" vdd_max="5.5" />
  </frequency_range>
  <frequency_range name="extended" special="low_power" >
    <frequency start="0"  end="16" vdd_min="1.8" vdd_max="3.6" />
    <frequency start="16" end="32" vdd_min="2.5" vdd_max="3.6" />
  </frequency_range>

  <voltages name="vpp"            min="8.0" max="9.0" nominal="9.0" />
  <voltages name="vdd_prog"       min="2.7" max="5.5" nominal="5.0"  />
  <voltages name="vdd_prog_write" min="2.7" max="5.5" nominal="5.0"  />

<!--* Memory ***************************************************************-->
  <memory name="code"         start="0x0000" end="0x07FF" />
  <memory name="user_ids"     start="0x8000" end="0x8003" rmask="0x3FFF"          />
  <memory name="debug_vector" start="0x8004" end="0x8004" />
  <memory name="device_id"    start="0x8006" end="0x8006" />
  <memory name="config"       start="0x8007" end="0x8008" />
  <memory name="calibration"  start="0x8009" end="0x800A" cal_opmask="0x0000" cal_opcode="0x0000" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="CONFIG1" wmask="0x3FFF" bvalue="0x3FFF" >
    <mask name="FOSC"  value="0x0003" >
      <value value="0x0000" name="LP"       def="_FOSC_INTOSC"     />
      <value value="0x0001" name="XT"       def="_FOSC_ECL"     />
      <value value="0x0002" name="HS"       def="_FOSC_ECM"     />
      <value value="0x0003" name="EC_IO"    def="_FOSC_ECH"  />
    </mask>
    <mask name="WDT"   value="0x0018" >
      <value value="0x0000" name="Off"      def="_WDTE_OFF"    />
      <value value="0x0008" name="Software" def="_WDTE_SWDTEN" />
      <value value="0x0010" name="On_run"   def="_WDTE_NSLEEP" />
      <value value="0x0018" name="On"       def="_WDTE_ON"     />
    </mask>
    <mask name="PWRTE" value="0x0020" >
      <value value="0x0000" name="On"  def="_PWRTE_ON"  />
      <value value="0x0020" name="Off" def="_PWRTE_OFF" />
    </mask>
    <mask name="MCLRE" value="0x0040" >
      <value value="0x0000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x0040" name="External" def="_MCLRE_ON"  />
    </mask>

    <mask name="CP"    value="0x0080" >
      <value value="0x0000" name="All" def="_CP_ON"  />
      <value value="0x0080" name="Off" def="_CP_OFF" />
    </mask>
    <mask name="BODEN" value="0x0600" >
      <value value="0x0000" name="Off"      def="_BOREN_OFF"    />
      <value value="0x0200" name="Software" def="_BOREN_SBODEN" />
      <value value="0x0400" name="On_run"   def="_BOREN_NSLEEP" />
      <value value="0x0600" name="On"       def="_BOREN_ON"     />
    </mask>
    <mask name="CLKOUTEN"  value="0x0800" >
      <value value="0x0000" name="On"   def="_CLKOUTEN_ON"  />
      <value value="0x0800" name="Off"  def="_CLKOUTEN_OFF" />
    </mask>
  </config>

  <config offset="0x1" name="CONFIG2" wmask="0x3FFF" bvalue="0x2E03" >
    <mask name="WRT"  value="0x0003" >
      <value value="0x0000" name="0000:07FF" def="_WRT_ALL"  />
      <value value="0x0001" name="0000:03FF" def="_WRT_HALF" />
      <value value="0x0002" name="0000:01FF" def="_WRT_BOOT" />
      <value value="0x0003" name="Off"       def="_WRT_OFF"  />
    </mask>
    <mask name="STVREN"   value="0x0200" >
      <value value="0x0000" name="Off" def="_STVREN_OFF" />
      <value value="0x0200" name="On"  def="_STVREN_ON"  />
    </mask>
    <mask name="BORV" value="0x0400" >
      <value value="0x0400" name="1.9" def="_BORV_19" />
      <value value="0x0000" name="2.5" def="_BORV_25" />
    </mask>

<!-- NOT_LPBOR is missing here 0x0000 and 0x00800 -->

    <mask name="DEBUG" value="0x1000" >
      <value value="0x0000" name="On"  def="_DEBUG_ON"  />
      <value value="0x1000" name="Off" def="_DEBUG_OFF" />
    </mask>
    <mask name="LVP"   value="0x2000" >
      <value value="0x0000" name="Off" def="_LVP_OFF" />
      <value value="0x2000" name="On"  def="_LVP_ON"  />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip ssop soic" nb_pins="20" >
    <pin index="1"  name="VDD" />
    <pin index="2"  name="RA5/CLKIN/T1CKI/NCO1CLK" />
    <pin index="3"  name="RA4/AN3/CLKOUT/T1G" />
    <pin index="4"  name="RA3/NOT_MCLR/VPP/CLC1IN0" />
    <pin index="5"  name="RC5/CCP1/CWG1A" />
    <pin index="6"  name="RC4/CWG1B/CLC2IN1" />
    <pin index="7"  name="RC3/AN7/CCP2/CLC2IN0" />
    <pin index="8"  name="RC6/AN8/CPS8" />
    <pin index="9"  name="RC7/AN9/CLC1IN1" />
    <pin index="10" name="RB7" />
    <pin index="11" name="RB6" />
    <pin index="12" name="RB5/AN11" />
    <pin index="13" name="RB4/AN10" />
    <pin index="14" name="RC2/AN6" />
    <pin index="15" name="RC1/AN5/CCP4/NCO1" />
    <pin index="16" name="RC0/AN4/CLC2" />
    <pin index="17" name="RA2/AN2/T0CKI/INT/CCP3/NOT_CWG1FLT/CLC1" />
    <pin index="18" name="RA1/AN1/VREF+/ICSPCLK" />
    <pin index="19" name="RA0/AN0/ICSPDAT" />
    <pin index="20" name="VSS" />
  </package>

  <package types="qfn" nb_pins="20" >
    <pin index="1"  name="RA3/NOT_MCLR/VPP/CLC1IN0" />
    <pin index="2"  name="RC5/CCP1/CWG1A" />
    <pin index="3"  name="RC4/CWG1B/CLC2IN1" />
    <pin index="4"  name="RC3/AN7/CCP2/CLC2IN0" />
    <pin index="5"  name="RC6/AN8/CPS8" />
    <pin index="6"  name="RC7/AN9/CLC1IN1" />
    <pin index="7"  name="RB7" />
    <pin index="8"  name="RB6" />
    <pin index="9"  name="RB5/AN11" />
    <pin index="10" name="RB4/AN10" />
    <pin index="11" name="RC2/AN6" />
    <pin index="12" name="RC1/AN5/CCP4/NCO1" />
    <pin index="13" name="RC0/AN4/CLC2" />
    <pin index="14" name="RA2/AN2/T0CKI/INT/CCP3/NOT_CWG1FLT/CLC1" />
    <pin index="15" name="RA1/AN1/VREF+/ICSPCLK" />
    <pin index="16" name="RA0/AN0/ICSPDAT" />
    <pin index="17" name="VSS" />
    <pin index="18" name="VDD" />
    <pin index="19" name="RA5/CLKIN/T1CKI/NCO1CLK" />
    <pin index="20" name="RA4/AN3/CLKOUT/T1G" />
  </package>


</device>

=== Petross404/piklab/src/devices/pic/xml_data/12F752.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2012 Nicolas Hadacek <hadacek@kde.org>                 *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="12F752" status="IP" memory_technology="FLASH" self_write="yes"
        architecture="midrange" id="0x1500" id_high_voltage="0x1520"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Documents ************************************************************-->
  <documents webpage="552818" datasheet="41576" progsheet="41561" erratas="80535" />

<!--* Checksums ************************************************************-->
  <checksums>
    <checksum protected="Off" bchecksum="0x3B79" cchecksum="0x0747" />
    <checksum protected="All" bchecksum="0x966B" cchecksum="0x0000" />
  </checksums>

<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" >
    <frequency start="0"  end="8"  vdd_min="2.0" vdd_max="5.5" />
    <frequency start="8"  end="10" vdd_min="3.0" vdd_max="5.5" />
    <frequency start="10" end="20" vdd_min="4.5" vdd_max="5.5" />
  </frequency_range>

  <frequency_range name="extended" special="high_voltage" >
    <frequency start="0"  end="8"  vdd_min="2.0" vdd_max="5.0" />
    <frequency start="8"  end="10" vdd_min="3.0" vdd_max="5.0" />
    <frequency start="10" end="20" vdd_min="4.0" vdd_max="5.0" />
  </frequency_range>

  <voltages name="vpp"            min="10"  max="13"  nominal="11.5" />
  <voltages name="vdd_prog"       min="4.5" max="5.5" nominal="5"    />
  <voltages name="vdd_prog_write" min="2"   max="5.5" nominal="5"    />

<!--* Memory ***************************************************************-->
  <memory name="code"         start="0x0000" end="0x03FF" />
  <memory name="calibration"  start="0x2008" end="0x2009" cal_opmask="0x0000" cal_opcode="0x0000" />
  <memory name="user_ids"     start="0x2000" end="0x2003" rmask="0x007F"      />
  <memory name="device_id"    start="0x2006" end="0x2006" />
  <memory name="config"       start="0x2007" end="0x2007" />
  <memory name="debug_vector" start="0x2004" end="0x2004" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="" wmask="0x3FFF" bvalue="0x3FFF" >
    <mask name="FOSC"   value="0x0001" >
      <value value="0x0000" name="INTRC" def="_FOSC0_INT" />
      <value value="0x0001" name="EC"    def="_FOSC0_EC"  />
    </mask>
    <mask name="WDT"    value="0x0008" >
      <value value="0x0000" name="Off" def="_WDT_OFF" />
      <value value="0x0008" name="On"  def="_WDT_ON"  />
    </mask>
    <mask name="PWRTE"  value="0x0010" >
      <value value="0x0000" name="On"  def="_PWRTE_ON"  />
      <value value="0x0010" name="Off" def="_PWRTE_OFF" />
    </mask>
    <mask name="MCLRE"  value="0x0020" >
      <value value="0x0000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x0020" name="External" def="_MCLRE_ON"  />
    </mask>
    <mask name="CP"     value="0x0040" >
      <value value="0x0000" name="All" def="_CP_ON"  />
      <value value="0x0040" name="Off" def="_CP_OFF" />
    </mask>
    <mask name="BODEN"  value="0x0300" >
      <value value="default" name="Off"    def="_BOREN_DIS"    />
      <value value="0x0200"  name="On_run" def="_BOREN_SLEEP_DIS" />
      <value value="0x0300"  name="On"     def="_BOREN_EN"     />
    </mask>
    <mask name="WRT"    value="0x0C00" >
      <value value="0x0000" name="0000:03FF" def="_WRT_ALL"  />
      <value value="0x0400" name="0000:01FF" def="_WRT_HALF" />
      <value value="0x0800" name="0000:00FF" def="_WRT_BOOT" />
      <value value="0x0C00" name="Off"       def="_WRT_OFF"  />
    </mask>
    <mask name="CLKOUTEN" value="0x1000" >
      <value value="0x0000" name="On"  def="_CLKOUTEN_ON"  />
      <value value="0x1000" name="Off" def="_CLKOUTEN_OFF" />
    </mask>
    <mask name="DEBUG" value="0x2000" >
      <value value="0x0000" name="On"  def="_DEBUG_ON"  />
      <value value="0x2000" name="Off" def="_DEBUG_OFF" />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip soic dfn" nb_pins="8" >
    <pin index="1" name="VDD" />
    <pin index="2" name="RA5" />
    <pin index="3" name="RA4" />
    <pin index="4" name="RA3/MCLR/VPP" />
    <pin index="5" name="RA2" />
    <pin index="6" name="RA1/ISCPCLK" />
    <pin index="7" name="RA0/ISCPDAT" />
    <pin index="8" name="VSS" />
  </package>

</device>
