=== Petross404/piklab/src/devices/pic/xml_data/pic.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- simple types definition -->
  <xs:simpleType name="hex">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9A-F]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hex4">
    <xs:restriction base="hex">
      <xs:length value="6"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="empty">
    <xs:restriction base="xs:string">
      <xs:length value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="word">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]+[A-Za-z0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EOL"/>
      <xs:enumeration value="NR"/>
      <xs:enumeration value="IP"/>
      <xs:enumeration value="Future"/>
      <xs:enumeration value="?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="memory_technology">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EE"/>
      <xs:enumeration value="EEE"/>
      <xs:enumeration value="EPROM"/>
      <xs:enumeration value="ROM"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="architecture">
    <xs:restriction base="xs:string">
      <xs:enumeration value="10X"/>
      <xs:enumeration value="16X"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="document_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
      <xs:pattern value="[?]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="errata_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+[a-z0-9]*"/>
      <xs:pattern value="er[a-z0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="erratas_type">
    <xs:list itemType="errata_type"/>
  </xs:simpleType>

  <xs:simpleType name="checksum_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="XOR4"/>
      <xs:enumeration value="XNOR7"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="frequency_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="commercial"/>
      <xs:enumeration value="industrial"/>
      <xs:enumeration value="extended"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frequency_special">
    <xs:restriction base="xs:string">
      <xs:enumeration value="low power"/>
      <xs:enumeration value="low voltage"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frequency_value">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="voltage_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vpp"/>
      <xs:enumeration value="vdd_prog"/>
      <xs:enumeration value="vdd_prog_write"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="voltage_value">
    <xs:restriction base="xs:float">
      <xs:minExclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="memory_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="program"/>
      <xs:enumeration value="eeprom"/>
      <xs:enumeration value="calibration"/>
      <xs:enumeration value="calibration_backup"/>
      <xs:enumeration value="user_ids"/>
      <xs:enumeration value="config"/>
      <xs:enumeration value="device_id"/>
      <xs:enumeration value="debug_vector"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hexfile_offset_unknown">
    <xs:restriction base="xs:string">
      <xs:enumeration value="?"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hexfile_offset">
    <xs:union memberTypes="hex hexfile_offset_unknown"/>
  </xs:simpleType>

  <xs:simpleType name="value_default_value">
    <xs:restriction base="xs:string">
      <xs:enumeration value="default"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="value_value">
    <xs:union memberTypes="hex value_default_value"/>
  </xs:simpleType>
  <xs:simpleType name="cname">
    <xs:restriction base="xs:string">
      <xs:pattern value="_[_0-9A-Za-z]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="cnames">
    <xs:list itemType="cname"/>
  </xs:simpleType>

  <xs:simpleType name="pin_name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z0-9-+]*(/[A-Z][A-Z0-9-+]*)*"/>
      <xs:pattern value="N/C"/>
      <xs:pattern value=""/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pin_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="dfns"/>
      <xs:enumeration value="mlf"/>
      <xs:enumeration value="mqfp"/>
      <xs:enumeration value="msop"/>
      <xs:enumeration value="pdip"/>
      <xs:enumeration value="plcc"/>
      <xs:enumeration value="qfn"/>
      <xs:enumeration value="sdip"/>
      <xs:enumeration value="soic"/>
      <xs:enumeration value="sot23"/>
      <xs:enumeration value="spdip"/>
      <xs:enumeration value="ssop"/>
      <xs:enumeration value="tqfp"/>
      <xs:enumeration value="tssop"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pin_types">
    <xs:list itemType="pin_type"/>
  </xs:simpleType>

<!-- complex types definition -->
  <xs:complexType name="DocumentsType">
    <xs:attribute name="webpage"       type="document_type" use="required"/>
    <xs:attribute name="datasheet"     type="document_type" use="required"/>
    <xs:attribute name="progsheet"     type="document_type" use="required"/>
    <xs:attribute name="erratas"       type="erratas_type"  use="required"/>
  </xs:complexType>

  <xs:complexType name="ChecksumType">
    <xs:attribute name="protected"       type="xs:string" />
    <xs:attribute name="type"            type="checksum_type" />
    <xs:attribute name="constant"        type="hex4" />
    <xs:attribute name="block_protected" type="xs:nonNegativeInteger"/>
    <xs:attribute name="bbsize"          type="xs:positiveInteger"/>
    <xs:attribute name="mprotected"      type="word"/>
    <xs:attribute name="bchecksum"       type="hex4" use="required"/>
    <xs:attribute name="cchecksum"       type="hex4" use="required"/>
  </xs:complexType>
  <xs:complexType name="ChecksumsType">
    <xs:sequence>
      <xs:element name="checksum" type="ChecksumType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="FrequencyType">
    <xs:attribute name="start"       type="frequency_value" use="required"/>
    <xs:attribute name="end"         type="frequency_value" use="required"/>
    <xs:attribute name="vdd_min"     type="voltage_value"   use="required"/>
    <xs:attribute name="vdd_min_end" type="voltage_value"                 />
    <xs:attribute name="vdd_max"     type="voltage_value"   use="required"/>
    <xs:attribute name="special"     type="xs:string"                     />
    <xs:attribute name="osc"         type="xs:string"                     />
  </xs:complexType>
  <xs:complexType name="FrequencyRangeType">
    <xs:sequence>
      <xs:element name="frequency" type="FrequencyType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="frequency_type"    use="required"/>
    <xs:attribute name="special" type="frequency_special"               />
  </xs:complexType>

  <xs:complexType name="VoltagesType">
    <xs:attribute name="name"    type="voltage_type"  use="required"/>
    <xs:attribute name="min"     type="voltage_value" use="required"/>
    <xs:attribute name="max"     type="voltage_value" use="required"/>
    <xs:attribute name="nominal" type="voltage_value" use="required"/>
  </xs:complexType>

  <xs:complexType name="MemoryType">
    <xs:attribute name="name"           type="memory_type"   use="required"/>
    <xs:attribute name="start"          type="hex"           use="required"/>
    <xs:attribute name="end"            type="hex"           use="required"/>
    <xs:attribute name="cal_opmask"     type="hex"                         />
    <xs:attribute name="cal_opcode"     type="hex"                         />
    <xs:attribute name="rmask"          type="hex"                         />
    <xs:attribute name="hexfile_offset" type="hexfile_offset"              />
  </xs:complexType>

  <xs:complexType name="ValueType">
    <xs:attribute name="name"    type="xs:string"   use="required"/>
    <xs:attribute name="value"   type="value_value" use="required"/>
    <xs:attribute name="cname"   type="cnames"                    />
    <xs:attribute name="ecnames" type="cnames"                    />
  </xs:complexType>
  <xs:complexType name="MaskType">
    <xs:sequence>
      <xs:element name="value" type="ValueType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"   type="word" use="required"/>
    <xs:attribute name="value"  type="hex"  use="required"/>
  </xs:complexType>
  <xs:complexType name="ConfigType">
    <xs:sequence>
      <xs:element name="mask" type="MaskType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"    type="xs:string" use="required"/>
    <xs:attribute name="offset"  type="hex"       use="required"/>
    <xs:attribute name="wmask"   type="hex"       use="required"/>
    <xs:attribute name="bvalue"  type="hex"       use="required"/>
    <xs:attribute name="cmask"   type="hex"                     />
    <xs:attribute name="pmask"   type="hex"                     />
    <xs:attribute name="icnames" type="cnames"                  />
  </xs:complexType>

  <xs:complexType name="PinType">
    <xs:attribute name="index" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="name"  type="pin_name"                         />
  </xs:complexType>
  <xs:complexType name="PackageType">
    <xs:sequence>
      <xs:element name="pin" type="PinType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="types"    type="pin_types"          use="required"/>
    <xs:attribute name="nb_pins"  type="xs:positiveInteger" use="required"/>
  </xs:complexType>

<!-- document -->
  <xs:complexType name="deviceType">
    <xs:sequence>
      <xs:element name="documents"       type="DocumentsType"      minOccurs="0"        />
      <xs:element name="checksums"       type="ChecksumsType"      minOccurs="0"        />
      <xs:element name="frequency_range" type="FrequencyRangeType" maxOccurs="unbounded"/>
      <xs:element name="voltages"        type="VoltagesType"       maxOccurs="unbounded"/>
      <xs:element name="memory"          type="MemoryType"         maxOccurs="unbounded"/>
      <xs:element name="config"          type="ConfigType"         maxOccurs="unbounded"/>
      <xs:element name="package"         type="PackageType"        maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name"              type="xs:string"         use="required"/>
    <xs:attribute name="alternative"       type="xs:string"                       />
    <xs:attribute name="document"          type="document_type"                   />
    <xs:attribute name="status"            type="status"            use="required"/>
    <xs:attribute name="memory_technology" type="memory_technology" use="required"/>
    <xs:attribute name="architecture"      type="architecture"      use="required"/>
    <xs:attribute name="pc"                type="xs:positiveInteger"              />
    <xs:attribute name="id"                type="hex4"                            />
  </xs:complexType>

  <xs:element name="device" type="deviceType"/>

</xs:schema>

=== Petross404/piklab/src/devices/pic/xml_data/16F526.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2005-2010 Nicolas Hadacek <hadacek@kde.org>            *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="16F526" status="IP" memory_technology="FLASH" architecture="baseline" pc="11"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Documents ************************************************************-->
  <documents webpage="530189" datasheet="41326" progsheet="41317" erratas="" />

<!--* Checksums ************************************************************-->
  <checksums>
    <checksum protected="Off"     bchecksum="0xED00" cchecksum="0xDB48" />
    <checksum protected="040:3FE" bchecksum="0xEDAF" cchecksum="0xD31B" />
  </checksums>

<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" >
    <frequency start="0"  end="4"  vdd_min="2"   vdd_max="5.5" />
    <frequency start="4"  end="10" vdd_min="3"   vdd_max="5.5" />
    <frequency start="10" end="20" vdd_min="4.5" vdd_max="5.5" />
  </frequency_range>

  <voltages name="vpp"      min="12.5" max="13.5" nominal="13" />
  <voltages name="vdd_prog" min="4.5"  max="5.5"  nominal="5"  />

<!--* Memory ***************************************************************-->
  <memory name="code"               start="0x000" end="0x3FE" />
  <memory name="calibration"        start="0x3FF" end="0x3FF" cal_opmask="0xF00"     cal_opcode="0xC00" />
  <memory name="eeprom"             start="0x400" end="0x43F" />
  <memory name="user_ids"           start="0x440" end="0x443" rmask="0x00F"          />
  <memory name="config"             start="0x7FF" end="0x7FF" hexfile_offset="0xFFF" />
  <memory name="calibration_backup" start="0x444" end="0x447" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="" wmask="0xFFF" bvalue="0x0FF" >
    <mask name="FOSC"   value="0x007" >
      <value value="0x000" name="LP"           def="_LP_OSC"             />
      <value value="0x001" name="XT"           def="_XT_OSC"             />
      <value value="0x002" name="HS"           def="_HS_OSC"             />
      <value value="0x003" name="EC_IO"        def="_EC_OSC"             />
      <value value="0x004" name="INTRC_IO"     def="_IntRC_OSC_RB4EN"    />
      <value value="0x005" name="INTRC_CLKOUT" def="_IntRC_OSC_CLKOUTEN" />
      <value value="0x006" name="EXTRC_IO"     def="_ExtRC_OSC_RB4EN"    />
      <value value="0x007" name="EXTRC_CLKOUT" def="_ExtRC_OSC_CLKOUTEN" />
    </mask>
    <mask name="WDT"    value="0x008" >
      <value value="0x000" name="Off" def="_WDT_OFF" />
      <value value="0x008" name="On"  def="_WDT_ON"  />
    </mask>
    <mask name="CP"     value="0x010" >
      <value value="0x000" name="040:3FE" def="_CP_ON"  />
      <value value="0x010" name="Off"     def="_CP_OFF" />
    </mask>
    <mask name="MCLRE"  value="0x020" >
      <value value="0x000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x020" name="External" def="_MCLRE_ON"  />
    </mask>
    <mask name="IOSCFS" value="0x040" >
      <value value="0x000" name="4MHZ" def="_IOSCFS_4MHZ" />
      <value value="0x040" name="8MHZ" def="_IOSCFS_8MHZ"  />
    </mask>
    <mask name="CPD"    value="0x080" >
      <value value="0x000" name="All" def="_CPDF_ON"  />
      <value value="0x080" name="Off" def="_CPDF_OFF" />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip soic tssop" nb_pins="14" >
    <pin index="1"  name="VDD"                   />
    <pin index="2"  name="RB5/OSC1/CLKIN"        />
    <pin index="3"  name="RB4/OSC2/CLKOUT"       />
    <pin index="4"  name="RB3/MCLR/VPP"          />
    <pin index="5"  name="RC5/T0CKI"             />
    <pin index="6"  name="RC4/C2OUT"             />
    <pin index="7"  name="RC3"                   />
    <pin index="8"  name="RC2/CVREF"             />
    <pin index="9"  name="RC1/C2IN-"             />
    <pin index="10" name="RC0/C2IN+"             />
    <pin index="11" name="RB2/AN2/C1OUT"         />
    <pin index="12" name="RB1/AN1/C1IN-/ICSPCLK" />
    <pin index="13" name="RB0/AN0/C1IN+/ICSPDAT" />
    <pin index="14" name="VSS"                   />
  </package>

  <package types="qfn" nb_pins="16" >
  </package>

</device>

=== Petross404/piklab/src/devices/pic/xml_data/10F204.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2005-2007 Nicolas Hadacek <hadacek@kde.org>            *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="10F204" document="020031" status="IP" memory_technology="FLASH" architecture="baseline" pc="9"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Checksums ************************************************************-->
  <checksums>
    <checksum protected="Off"     bchecksum="0xEF1D" cchecksum="0xDD65" />
    <checksum protected="040:0FE" bchecksum="0xEEF1" cchecksum="0xD45D" />
  </checksums>

<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" >
    <frequency start="4" end="4" vdd_min="2" vdd_max="5.5" />
  </frequency_range>

  <voltages name="vpp"      min="12.5" max="13.5" nominal="13" />
  <voltages name="vdd_prog" min="4.5"  max="5.5"  nominal="5"  />

<!--* Memory ***************************************************************-->
  <memory name="code"            start="0x000" end="0x0FE" />
  <memory name="calibration"        start="0x0FF" end="0x0FF" cal_opmask="0xF00"     cal_opcode="0xC00" />
  <memory name="user_ids"           start="0x100" end="0x103" rmask="0x00F"          />
  <memory name="config"             start="0x1FF" end="0x1FF" hexfile_offset="0xFFF" />
  <memory name="calibration_backup" start="0x104" end="0x104" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="" wmask="0xFFF" bvalue="0x01F" cmask="0x01C" >
    <mask name="FOSC"  value="0x003" >
      <value value="default" name="invalid" />
      <value value="0x003" name="INTRC" def="_IntRC_OSC" />
    </mask>
    <mask name="WDT"   value="0x004" >
      <value value="0x000" name="Off" def="_WDT_OFF" />
      <value value="0x004" name="On"  def="_WDT_ON"  />
    </mask>
    <mask name="CP"    value="0x008" >
      <value value="0x000" name="040:0FE" def="_CP_ON"  />
      <value value="0x008" name="Off"     def="_CP_OFF" />
    </mask>
    <mask name="MCLRE" value="0x010" >
      <value value="0x000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x010" name="External" def="_MCLRE_ON"  />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip"  nb_pins="8" >
    <pin index="1" name="N/C"                  />
    <pin index="2" name="VDD"                  />
    <pin index="3" name="GP2/T0CKI/FOSC4/COUT" />
    <pin index="4" name="GP1/ISCPCLK/CIN-"     />
    <pin index="5" name="GP0/ISCPDAT/CIN+"     />
    <pin index="6" name="N/C"                  />
    <pin index="7" name="VSS"                  />
    <pin index="8" name="GP3/MCLR/VPP"         />
  </package>

  <package types="sot23" nb_pins="6" >
    <pin index="1" name="GP0/ISCPDAT/CIN+"     />
    <pin index="2" name="VSS"                  />
    <pin index="3" name="GP1/ISCPCLK/CIN-"     />
    <pin index="4" name="GP2/T0CKI/FOSC4/COUT" />
    <pin index="5" name="VDD"                  />
    <pin index="6" name="GP3/MCLR/VPP"         />
  </package>

</device>

=== Petross404/piklab/src/devices/pic/xml_data/16F1937.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--************************************************************************-->
<!--* Copyright (C) 2010 Nicolas Hadacek <hadacek@kde.org>                 *-->
<!--*                                                                      *-->
<!--* This program is free software; you can redistribute it and/or modify *-->
<!--* it under the terms of the GNU General Public License as published by *-->
<!--* the Free Software Foundation; either version 2 of the License, or    *-->
<!--* (at your option) any later version.                                  *-->
<!--************************************************************************-->
<device name="16F1937" status="IP" memory_technology="FLASH" self_write="yes"
        architecture="emidrange" id="0x2380" id_low_power="0x2480"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pic.xsd'>

<!--* Documents ************************************************************-->
  <documents webpage="538149" datasheet="41364" progsheet="41397" erratas="80479" />

<!--* Checksums ************************************************************-->

<!--* Operating characteristics ********************************************-->
  <frequency_range name="extended" >
    <frequency start="0"  end="16" vdd_min="1.8" vdd_max="5.5" />
    <frequency start="16" end="32" vdd_min="2.3" vdd_max="5.5" />
  </frequency_range>
  <frequency_range name="extended" special="low_power" >
    <frequency start="0"  end="16" vdd_min="1.8" vdd_max="3.6" />
    <frequency start="16" end="32" vdd_min="2.3" vdd_max="3.6" />
  </frequency_range>

  <voltages name="vpp"            min="8.0" max="9.0" nominal="9.0" />
  <voltages name="vdd_prog"       min="2.7" max="5.5" nominal="5.0"  />
  <voltages name="vdd_prog_write" min="2.1" max="5.5" nominal="5.0"  />

<!--* Memory ***************************************************************-->
  <memory name="code"         start="0x0000" end="0x1FFF" />
  <memory name="user_ids"     start="0x8000" end="0x8003" rmask="0x3FFF"          />
  <memory name="debug_vector" start="0x8004" end="0x8004" />
  <memory name="device_id"    start="0x8006" end="0x8006" />
  <memory name="config"       start="0x8007" end="0x8008" />
  <memory name="calibration"  start="0x8009" end="0x800A" cal_opmask="0x0000" cal_opcode="0x0000" />
  <memory name="eeprom"       start="0x0000" end="0x00FF" hexfile_offset="0xF000" />

<!--* Configuration bits ***************************************************-->
  <config offset="0x0" name="CONFIG1" wmask="0x3FFF" bvalue="0x3FFF" >
    <mask name="FOSC"  value="0x0007" >
      <value value="0x0000" name="LP"       def="_FOSC_LP"     />
      <value value="0x0001" name="XT"       def="_FOSC_XT"     />
      <value value="0x0002" name="HS"       def="_FOSC_HS"     />
      <value value="0x0003" name="EC_IO"    def="_FOSC_EXTRC"  />
      <value value="0x0004" name="INTRC_IO" def="_FOSC_INTOSC" />
      <value value="0x0005" name="EC_LP"    def="_FOSC_ECL"    />
      <value value="0x0006" name="EC_MP"    def="_FOEC_ECM"    />
      <value value="0x0007" name="EC_HP"    def="_FOSC_ECH"    />
    </mask>
    <mask name="WDT"   value="0x0018" >
      <value value="0x0000" name="Off"      def="_WDTE_OFF"    />
      <value value="0x0008" name="Software" def="_WDTE_SWDTEN" />
      <value value="0x0010" name="On_run"   def="_WDTE_NSLEEP" />
      <value value="0x0018" name="On"       def="_WDTE_ON"     />
    </mask>
    <mask name="PWRTE" value="0x0020" >
      <value value="0x0000" name="On"  def="_nPWRTE_ON"  />
      <value value="0x0020" name="Off" def="_nPWRTE_OFF" />
    </mask>
    <mask name="MCLRE" value="0x0040" >
      <value value="0x0000" name="Internal" def="_MCLRE_OFF" />
      <value value="0x0040" name="External" def="_MCLRE_ON"  />
    </mask>
    <mask name="CP"    value="0x0080" >
      <value value="0x0000" name="All" def="_CP_ON"  />
      <value value="0x0080" name="Off" def="_CP_OFF" />
    </mask>
    <mask name="CPD"   value="0x0100" >
      <value value="0x0000" name="All" def="_CPD_ON"  />
      <value value="0x0100" name="Off" def="_CPD_OFF" />
    </mask>
    <mask name="BODEN" value="0x0600" >
      <value value="0x0000" name="Off"      def="_BOREN_OFF"    />
      <value value="0x0200" name="Software" def="_BOREN_SBODEN" />
      <value value="0x0400" name="On_run"   def="_BOREN_NSLEEP" />
      <value value="0x0600" name="On"       def="_BOREN_ON"     />
    </mask>
    <mask name="CLKOUTEN"  value="0x0800" >
      <value value="0x0000" name="On"   def="_CLKOUTEN_ON"  />
      <value value="0x0800" name="Off"  def="_CLKOUTEN_OFF" />
    </mask>
    <mask name="IESO"  value="0x1000" >
      <value value="0x0000" name="Off" def="_IESO_OFF" />
      <value value="0x1000" name="On"  def="_IESO_ON"  />
    </mask>
    <mask name="FCMEN" value="0x2000" >
      <value value="0x0000" name="Off" def="_FCMEN_OFF" />
      <value value="0x2000" name="On"  def="_FCMEN_ON"  />
    </mask>
  </config>

  <config offset="0x1" name="CONFIG2" wmask="0x3FFF" bvalue="0x3713" >
    <mask name="WRT"  value="0x0003" >
      <value value="0x0000" name="0000:1FFF" def="_WRT_ALL"  />
      <value value="0x0001" name="0000:0FFF" def="_WRT_HALF" />
      <value value="0x0002" name="0000:01FF" def="_WRT_BOOT" />
      <value value="0x0003" name="Off"       def="_WRT_OFF"  />
    </mask>
    <mask name="VCAP"  value="0x0030" >
      <value value="0x0000" name="RA0" def="_VCAPEN_RA0" />
      <value value="0x0010" name="RA5" def="_VCAPEN_RA5" />
      <value value="0x0020" name="RA6" def="_VCAPEN_RA6" />
      <value value="0x0030" name="Off" def="_VCAPEN_OFF" />
    </mask>
    <mask name="PLLEN"   value="0x0100" >
      <value value="0x0000" name="Off" def="_PLLEN_OFF" />
      <value value="0x0100" name="On"  def="_PLLEN_ON"  />
    </mask>
    <mask name="STVREN"   value="0x0200" >
      <value value="0x0000" name="Off" def="_STVREN_OFF" />
      <value value="0x0200" name="On"  def="_STVREN_ON"  />
    </mask>
    <mask name="BORV" value="0x0400" >
      <value value="0x0400" name="1.9" def="_BORV_19" />
      <value value="0x0000" name="2.5" def="_BORV_25" />
    </mask>
    <mask name="DEBUG" value="0x1000" >
      <value value="0x0000" name="On"  def="_nDEBUG_ON"  />
      <value value="0x1000" name="Off" def="_nDEBUG_OFF" />
    </mask>
    <mask name="LVP"   value="0x2000" >
      <value value="0x0000" name="Off" def="_LVP_OFF" />
      <value value="0x2000" name="On"  def="_LVP_ON"  />
    </mask>
  </config>

<!--* Packages *************************************************************-->
  <package types="pdip" nb_pins="40" >
  </package>
  <package types="qfn" nb_pins="44" >
  </package>

</device>
